//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdsTrackingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel
    {
        public int CarModelId { get; set; }
        public int CarBrandId { get; set; }
        public string CarModelName { get; set; }
        public string CarModelValue { get; set; }

        public virtual CarBrand CarBrand { get; set; }
    }
}
