//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdsTrackingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebPage()
        {
            this.CarBrands = new HashSet<CarBrand>();
        }
    
        public int WebPageId { get; set; }
        public string WebPageName { get; set; }
        public string HomePageAdress { get; set; }
        public string CarBrandKey { get; set; }
        public string CarModelKey { get; set; }
        public string CarYearsFromKey { get; set; }
        public string CarYearsToKey { get; set; }
        public string CarPriceFromKey { get; set; }
        public string CarPriceToKey { get; set; }
        public string CarFuelKey { get; set; }
        public string AdditionalKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarBrand> CarBrands { get; set; }
    }
}
